export const TESTIMONIALS = [
    {
        name: "Dr. Sarah Martinez",
        role: "Practice Owner",
        company: "Paws & Claws Veterinary",
        companyUrl: "https://pawsandclaws.com",
        image: "/images/testimonials/person1.jpg",
        content: "Prevenue reduced our no-shows by 35% in just 6 weeks. As an early adopter, I'm amazed by how quickly their AI learned our patterns.",
        time: "2:15 PM",
        date: "Dec 15, 2025",
    },
    {
        name: "Maria Rodriguez",
        role: "Salon Manager",
        company: "Luxe Hair Studio",
        companyUrl: "https://luxehairstudio.com",
        image: "/images/testimonials/person2.jpg",
        content: "We joined Prevenue in their first month and have already recovered $8K in lost revenue. The smart overbooking feature is brilliant.",
        time: "11:30 AM",
        date: "Dec 20, 2025",
    },
    {
        name: "Dr. James Chen",
        role: "Veterinarian",
        company: "City Animal Hospital",
        companyUrl: "https://cityanimalhospital.com",
        image: "/images/testimonials/person3.jpg",
        content: "Being one of their beta customers was the best decision. Their insight about cat vs dog appointment patterns revolutionized our scheduling.",
        time: "9:45 AM",
        date: "Nov 28, 2025",
    },
    {
        name: "Jennifer Walsh",
        role: "Spa Director",
        company: "Serenity Day Spa",
        companyUrl: "https://serenitydayspa.com",
        image: "/images/testimonials/person4.jpg",
        content: "Prevenue's team personally onboarded us in September. The automated reminder system has completely transformed our client reliability.",
        time: "4:20 PM",
        date: "Dec 10, 2025",
    },
    {
        name: "Dr. Robert Kim",
        role: "Practice Manager",
        company: "Wellness Veterinary Group",
        companyUrl: "https://wellnessvetgroup.com",
        image: "/images/testimonials/person1.jpg",
        content: "Implemented Prevenue 3 months ago and it's already paid for itself twice over. Their young team is incredibly responsive and innovative.",
        time: "1:10 PM",
        date: "Dec 22, 2025",
    },
    {
        name: "Lisa Thompson",
        role: "Owner",
        company: "Elite Beauty Lounge",
        companyUrl: "https://elitebeautylounge.com",
        image: "/images/testimonials/person2.jpg",
        content: "As an early customer from their August launch, I've seen them evolve rapidly. The consequence management system has trained our clients perfectly.",
        time: "3:50 PM",
        date: "Dec 18, 2025",
    },
];
