export const TESTIMONIALS = [
    {
        name: "Dr. Sarah Martinez",
        role: "Practice Owner",
        company: "Paws & Claws Veterinary",
        companyUrl: "https://pawsandclaws.com",
        image: "/images/testimonials/person1.jpg",
        content: "i don't have to answer calls anymore. Prevenue books everything, sends reminders, does follow-ups. And we stopped losing money from people not showing up.",
        time: "2:15 PM",
        date: "Dec 15, 2025",
    },
    {
        name: "Maria Rodriguez",
        role: "Salon Manager",
        company: "Luxe Hair Studio",
        companyUrl: "https://luxehairstudio.com",
        image: "/images/testimonials/person2.jpg",
        content: "We got back 15 hours a week. No more phone tag with clients. Plus we made an extra $8K because fewer people bail on appointments.",
        time: "11:30 AM",
        date: "Dec 20, 2025",
    },
    {
        name: "Dr. James Chen",
        role: "Veterinarian",
        company: "City Animal Hospital",
        companyUrl: "https://cityanimalhospital.com",
        image: "/images/testimonials/person3.jpg",
        content: "It handles all our booking stuff. Calls, scheduling, reminders, the works. The best part? Way fewer no-shows eating into our revenue.",
        time: "9:45 AM",
        date: "Nov 28, 2025",
    },
    {
        name: "Jennifer Walsh",
        role: "Spa Director",
        company: "Serenity Day Spa",
        companyUrl: "https://serenitydayspa.com",
        image: "/images/testimonials/person4.jpg",
        content: "Set it up in September. Now our booking runs itself and clients actually show up. The team was super helpful getting us started.",
        time: "4:20 PM",
        date: "Dec 10, 2025",
    },
    {
        name: "Dr. Robert Kim",
        role: "Practice Manager",
        company: "Wellness Veterinary Group",
        companyUrl: "https://wellnessvetgroup.com",
        image: "/images/testimonials/person1.jpg",
        content: "Three months in and we already made our money back twice. The booking runs smooth and no-shows dropped big time.",
        time: "1:10 PM",
        date: "Dec 22, 2025",
    },
    {
        name: "Lisa Thompson",
        role: "Owner",
        company: "Elite Beauty Lounge",
        companyUrl: "https://elitebeautylounge.com",
        image: "/images/testimonials/person2.jpg",
        content: "Been with them since August. The booking system just works and our clients learned to stop flaking. Makes a real difference.",
        time: "3:50 PM",
        date: "Dec 18, 2025",
    },
];
