export const BLOGS = [
    {
        title: "Structured Layers",
        desc: "Organize your design system with clear, maintainable layers for better scalability.",
        image: "/images/blog1.svg",
        category: "Design System",
        author: "Sarah Leeman",
        authorRole: "Marketing Leader",
        authorCompany: "Mailchimp",
        authorCompanyUrl: "https://mailchimp.com",
        authorImage: "/images/person-one.jpg",
    },
    {
        title: "Maximize Revenue with Prevenue",
        desc: "Learn how AI-powered no-show prevention can protect your practice's revenue and improve client accountability.",
        image: "/images/blog2.svg",
        category: "Revenue Protection",
        author: "John Doe",
        authorRole: "Product Manager",
        authorCompany: "Google",
        authorCompanyUrl: "https://google.com",
        authorImage: "/images/person-three.jpg",
    },
    {
        title: "Technology Trends 2025",
        desc: "Stay ahead with the latest trends and innovations shaping the tech industry.",
        image: "/images/blog3.svg",
        category: "Technology",
        author: "Emily Johnson",
        authorRole: "Software Engineer",
        authorCompany: "Microsoft",
        authorCompanyUrl: "https://microsoft.com",
        authorImage: "/images/person-four.jpg",
    },
    {
        title: "Effective Team Collaboration",
        desc: "Boost productivity with proven strategies for seamless team collaboration.",
        image: "/images/blog1.svg",
        category: "Productivity",
        author: "Michael Smith",
        authorRole: "UX Designer",
        authorCompany: "Adobe",
        authorCompanyUrl: "https://adobe.com",
        authorImage: "/images/person-five.jpg",
    },
];
